version: 2
updates:
  - package-ecosystem: pip
    directory: /manager
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /manager
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
